# This is a basic workflow to help you get started with Actions

name: Generate download folder to easily import.

# Controls when the workflow will run
on:
   workflow_dispatch:
   release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Create the folder to download and import
        run: |
          mkdir "Graphite You"
          cp theme.css manifest.json "Graphite You"
          zip -r "Graphite\ You.zip" "Graphite You"

      # Runs a set of commands using the runners shell
      - name: Add zip folder to latest release
        run: gh release upload "${{ github.event.release.tag_name }}" "Graphite You.zip" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
